# Streamlit Cloud Secrets Configuration
# Copy this content to your Streamlit Cloud app's "Secrets" section
# Go to: https://share.streamlit.io/ > Your App > Settings > Secrets

# Replace with your actual Groq API key from https://console.groq.com/
GROQ_API_KEY = "your_actual_groq_api_key_here"

# Optional: Add other configuration if needed
# DATABASE_URL = "your_database_connection_string"
# DEBUG_MODE = false
