# Streamlit Cloud Configuration
# This file is used by Streamlit Cloud for deployment

[general]
email = ""

[server]
headless = true
enableCORS = false
port = 8501

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
